name: Dump

on: [push]

jobs:
  dump:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Dump env to file
        run: |
          mkdir -p /tmp/x
          env > /tmp/x/env.txt
          echo "DONE" > /tmp/x/complete.txt
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: env-dump
          path: /tmp/x/
